version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - target: 80
        published: 80
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf

  flask-app:
    container_name: flask-app
    image: flask-app:latest
    build: ./flask-app
    environment: 
      YOUR_NAME: Andrew
      MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
      
  trio-mysql:
    container_name: trio-mysql
    image: trio-mysql:latest
    build: ./db
    volumes:
      - "db-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
      MYSQL_DATABASE: flask-db

volumes:
  db-data:
